# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"
    container_name: backend

  frontends:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontends
    ports:
      - "8080:8080"
    depends_on:
      - backend
    container_name: frontends

