[server_settings]
address = "0.0.0.0"
port = 3000
database_url = "sqlite:random-words.db"
allowed_origins = [
  "http://localhost:1420",
  "http://localhost:5173",
  "http://127.0.0.1:1420",
  "http://127.0.0.1:5173",
]

[compression]
brotli = true
gzip = true

[jwt_settings]
token_expiration_minutes = 5
secret = "default_jwt_secret_change_in_production"

[api_limits]
rate_limit_per_second = 500
burst_size = 500
request_timeout = 500
request_body_limit_kilobytes = 10240

[openapi]
enable_swagger_ui = true
enable_redoc = true
enable_scalar = true
enable_rapidoc = true
