address = "0.0.0.0"
port = 3000
database_url = "sqlite:random-words.db"

[jwt_settings]
token_expiration_minutes = 5
secret = "default_jwt_secret_change_in_production"

[security_limits]
rate_limit_per_second = 5

[openapi]
enable_swagger_ui = false
enable_redoc = false
enable_scalar = false
enable_rapidoc = false
